[package]
name = "skia-engine-macro"
description = "Macros for skia-engine"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/skia-engine-macro"
authors.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[lib]
proc-macro = true

[dependencies]
skia-engine-core = { workspace = true }

quote = { workspace = true }
skia-safe = { workspace = true }
syn = { workspace = true }
syn-rsx = { workspace = true }
proc-macro2 = { workspace = true }
