[package]
name = "skia-engine"
description = "Easier Skia manipulation in rust"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/skia-engine"
authors.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[dependencies]
skia-engine-core = { workspace = true }
skia-engine-macro = { workspace = true }
