[package]
name = "skia-engine-core"
description = "Core crate for skia-engine"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/skia-engine-core"
authors.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[dependencies]
skia-safe = { workspace = true }
hyper = { version = "1.11.1", optional = true }
reqwest = { version = "0.13.5", features = ["blocking"], optional = true }
ureq = { version = "3.4.2", optional = true }

[features]
default = []
# Use reqwest as the HTTP client for fetching images with the image Node
reqwest = ["dep:reqwest"]
# Use ureq as the HTTP client for fetching images with the image Node
ureq = ["dep:ureq"]
# Throw errors when fetching images with the image Node (useful for debugging)
enable-image-errors = []
