[package]
name = "skia-engine-core"
description = "Core crate for skia-engine"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/skia-engine-core"
authors.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[dependencies]
skia-safe = { workspace = true }
